### ISSUE TITLE
ValueRangeValidator not detecting valid values

### ISSUE THREAD

**Issue by jchen1624** [rubberduck-vba/MVVM#4]
Hi there,

Thanks for putting together this project, Mat. I thought your inititial MVVM code looked great, and this iteration brings some nice additions. I'm looking forward to seeing how far you take it.

Following is a minor issue I came across while testing:

I tried to create a textbox that accepts only integer values between 0 and 100. In my test, any value I enter triggers the invalid value error message.

![image](https://user-images.githubusercontent.com/25762235/97355930-8b379e00-188f-11eb-94cc-8c92f72c354f.png)

There wasn't an example of this particular validator, so I immitated how some of the other binding parameters were setup. Most likely, I'm using the wrong syntax. Here are the steps I took:

- In ExampleView Designer, add a textbox and name it "textbox2"

- In ExampleView Code-behind, add a property binding:

```
        .BindPropertyPath ViewModel, "SomeNumber", Me.TextBox2, _
            UpdateTrigger:=OnKeyPress, _
            Validator:=ValueRangeValidator.Create(Min:=0, max:=100), _
            ValidationAdorner:=ValidationErrorAdorner.Create( _
                Target:=Me.TextBox2, _
                TargetFormatter:=ValidationErrorFormatter.WithErrorBorderColor.WithErrorBackgroundColor)
```

- In the ExampleViewModel, add the property "SomeNumber" to the custom type:

```
Private Type TViewModel
    Notifier As INotifyPropertyChanged
    
    SomeCommand As ICommand
    SomeFilePath As String
    SomeAmount As Currency
    SomeDate As Date
    SomeProperty As String
    SomeOption As Boolean
    SomeOtherOption As Boolean
    SomeItems As Variant
    SelectedItemText As String
    SelectedItemIndex As Long
    BooleanProperty As Boolean
    ByteProperty As Byte
    CurrencyProperty As Currency
    DateProperty As Date
    DoubleProperty As Double
    LongProperty As Long
    StringProperty As String
    
    SomeNumber As Long
End Type
```

- In the ExampleViewModel, add the property getter and setter:

```
Public Property Get SomeNumber() As Long
    SomeNumber = this.SomeNumber
End Property

Public Property Let SomeNumber(ByVal RHS As Long)
    If this.SomeNumber <> RHS Then
        this.SomeNumber = RHS
        OnPropertyChanged "SomeNumber"
    End If
End Property
```

- In Example module, execute the "run()" sub. Now enter a valid a number between 0 and 100. When you press "tab" to move to the next control, the invalid value error message will display. 

That's it. Thanks for any help on this.
-Jay

**Comment by retailcoder** [comment]
Hey Jay, thanks for playing with this code!

The `OnKeyPress` binding mode is being overridden to `IValueValidator.UpdateTrigger` by the `ValueRangeValidator`:

```vba
'@Description "Using this validator in a property binding will coerce it into using this update trigger."
Public Property Get Trigger() As BindingUpdateSourceTrigger
End Property
```

The `ValueRangeValidator` sets the binding mode to `OnExit`:

```vba
Private Property Get IValueValidator_Trigger() As BindingUpdateSourceTrigger
    IValueValidator_Trigger = OnExit
End Property
```

I reproduced the problem with this binding:

```vba
        .TextBoxFor BindingPath.Create(This.ViewModel, "StringProperty"), _
                    Validator:=ValueRangeValidator.Create(0, 100), _
                    TitleSource:="Some String:"
```

Setting a breakpoint in the validator shows that the problem is that the comparison is being done against `String` values, so the string "50" indeed fails to validate (since the strings "0" and "100" both come before "50" in an alphabetical sort).

The `ValueRangeValidator` could smarten up a bit and verify whether it's dealing with text-as-numbers before proceeding; perhaps that should be configurable, say, by taking in some `Enum` value in the `Create` method:

```vba
        .TextBoxFor BindingPath.Create(This.ViewModel, "StringProperty"), _
                    Validator:=ValueRangeValidator.Create(0, 100, SortTextAsNumbers), _
                    TitleSource:="Some String:"
```

Thoughts? Alternatively, an `IValueConverter` could be implemented to convert the numeric value to/from an actual number before it gets to the validator.
