### ISSUE TITLE
Why ConnectToConnectionPoint API?

### ISSUE THREAD

**Issue by cristianbuse** [rubberduck-vba/MVVM#9]
I can see the benefit of using ```ConnectToConnectionPoint``` but is it really necessary? Is there any event that cannot be captured using ```WithEvents```? I tend to use a general purpose class that captures the events I need. Example [here](https://github.com/cristianbuse/VBA-UserForm-MouseScroll/blob/master/Code%20Modules/MouseOverControl.cls). The downside is that events need to be repeated for each control type but the upside is that there is no need for an extra dependancy and it works on MAC. Am I missing anything?

**Comment by retailcoder** [comment]
Hi, and sorry for the delayed response (looks like I forgot to setup webhooks on this repo!)... the API is what made MVVM possible in the first place (when I saw [this post on Stack Overflow](https://stackoverflow.com/q/61855925/1188513) the first thing I thought was "OMG that makes MVVM a possibility!" and that's what prompted me to explore MVVM in VBA), because without it there is no way to handle the events of `MSForms.Control`, of which the `Exit` event is needed in order to be able to configure bindings that work nicely; bindings are certainly possible without it, but without being able to hande `Exit` I'm not sure how it would be possible to *cancel* exiting a `TextBox` when its bound value fails validation.

**Comment by retailcoder** [comment]
That said I'm not sure this MVVM project _should_ be written in VBA. I'm thinking [twinBASIC](https://www.twinbasic.com/) could be the game-changer we need to make an actual MVVM library/framework that VBA can use (without importing 150 classes into one's project!).

**Comment by cristianbuse** [comment]
That's what I was missing. I didn't know the ```Exit``` event is not exposed. Makes perfect sense now. twinBasic looks cool. Thanks! And sorry, I should have investigated before opening an issue but I guess I was too lazy!
